### ISSUE TITLE
Assignment section cards not displaying correctly

### ISSUE THREAD

**Issue by marissarousseau** [marissarousseau/canvasdarkmode#16]
![darkanvasbug](https://user-images.githubusercontent.com/54009117/80508377-f8509200-8945-11ea-86d0-da564dd54ea6.png)
The issue is likely due to code inverting the header cards when they don't need to be.

**Comment by HypeRayy** [comment]
Thanks again for taking this bug on board! -Rayyan

**Comment by marissarousseau** [comment]
Closing this issue. See #20 for more information. This bug will be addressed in the redesigned version of this extension.
