### ISSUE TITLE
Toggle to turn off dark theme

### ISSUE THREAD

**Issue by marissarousseau** [marissarousseau/canvasdarkmode#17]
Would require adding a Chrome event listener. Not sure how this would work in Firefox. 

Three options:
- On clicking the extension icon
- On clicking a button inside of the popup
- Right click context menu option?

**Comment by josephemorgan91** [comment]
Came here to request this same issue, glad to see it's already open.

**Comment by marissarousseau** [comment]
> Came here to request this same issue, glad to see it's already open.

Glad to see more support for this idea, it's definitely something I considered in the past but ultimately never got to. I'm currently looking into, might look into getting some help with it with someone more experienced with event listeners with Chrome extensions.

**Comment by marissarousseau** [comment]
Closing this issue. Please see #20 for more information. The extension is being redesigned and a toggle to disable the theme will be included in the redesign.
