### ISSUE TITLE
Text that is black does not show correctly when using dark mode.

### ISSUE THREAD

**Issue by HypeRayy** [marissarousseau/canvasdarkmode#19]
When viewing assignments that use black font, it does not show unless i highlight the text using my cursor.

![image](https://user-images.githubusercontent.com/11124303/81047043-f7e36880-8efc-11ea-8138-da3e0c3d1f04.png)

(see huge missing chunks in text) besdies the highlighted text.

**Comment by marissarousseau** [comment]
Hey there. Thanks for opening this issue. This is a known issue that I've tried to figure out for a while know. Since the extension is being completely rewritten from scratch currently I'm hoping this will fix the problem.

**Comment by marissarousseau** [comment]
Closing this issue. Please see #20 for more information. This bug will be addressed in a complete redesign on the extension.
