### ISSUE TITLE
Discussion entries are bright

### ISSUE THREAD

**Issue by CraigRobertWhite** [marissarousseau/canvasdarkmode#6]
![image](https://user-images.githubusercontent.com/22895938/73694309-c9f44b00-46a5-11ea-8b46-fca26523e2b0.png)
The image above is how a discussion entry currently appears on Google Chrome version 79.0.3945.130 on a Windows 10 64-bit PC.

The background for discussion entries appears to still have a white background.

A potential fix for this would be the following CSS style attribute changes:
- `.discussion_entry`
   - `background: black` instead of `background: white`
- `.discussion_entries entry`
   - `background: black` instead of `background: #fff`
   - `border: 1px solid black` instead of `border: 1px solid #C7CDD1`
- `.replies`
   - `border-left: solid black 16px` instead of `border-left: solid #f2f2f2 16px`

These changes make the discussion entries appear as such:
![image](https://user-images.githubusercontent.com/22895938/73694220-a16c5100-46a5-11ea-88bf-371d806859a8.png)

**Comment by marissarousseau** [comment]
Thanks for catching this and testing a fix.  It looks like I missed the Discussion pages because none of my courses currently use them.  This can be added for the next release, coming sometime this week hopefully.

**Comment by marissarousseau** [comment]
This issue is fixed in v1.1.5, which is currently available on Firefox Addons. It is also awaiting for approval on the Chrome Web Store and Opera Addons.
